name: Pipeline de CI - Olá Mundo DevOps
on:
  push: 
    branches: ["main"] 
  pull_request: 
    branches: ["main"] 
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22" 
          cache: "npm" 
      - name: Instalar Dependências
        run: npm install
      - name: Rodar Testes
        run: npm test
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: ./Dockerfile 
          push: false 
          tags: ola-devops:latest
